### ISSUE TITLE
Accessing current

### ISSUE THREAD

**Issue by kesne** [global-env/proposal#1]
Right now we access the current value of the env on `CURRENT`. Should we consider using a lowercase name `current` to better align with `prod`/`dev`/`is`? The caps align more with `NODE_ENV`, but I'm not sure that's important.

**Comment by milesj** [comment]
I've actually thought about capitalizing all properties, as they act more like true constants. `env.DEV`, `env.PROD`, etc.

**Comment by kesne** [comment]
That's true, although I'd rather keep us aligned so that the proposal feels more at home in ES. I think cap names aren't super frequently used in ES. The closest thing I can think of is well known symbols, which use camelcase.
