### ISSUE TITLE
Use full names for prod and dev.

### ISSUE THREAD

**Issue by kesne** [global-env/proposal#2]
Right now the proposal uses `prod` and `dev` for matching `production` and `development`. This seems a little weird. I think we should instead expose `production` and `development`, so that you know exactly what env variables you're matching against.

**Comment by milesj** [comment]
I'm leaning towards `dev` and `prod` as it's far less to type. It's one of the primary reasons that `__DEV__` replaced `process.env.NODE_ENV !== 'development'`. People love shorthand syntax.

**Comment by kesne** [comment]
It's way less to type, but `env.production` and `env.development` is still pretty short, and it keeps the property name aligned with the `NODE_ENV` value. If you set `NODE_ENV=prod` then would `env.prod` resolve to true? I'd expect to to.

**Comment by milesj** [comment]
Perhaps that's another discussion. Should our `env.prod` flag support multiple values?

```
dev: (ENV === 'dev' || ENV === 'develop' || ENV === 'development'),
prod: (ENV === 'prod' || ENV === 'production'),
```

**Comment by kesne** [comment]
I think this is best solved by using `production` instead of `prod`. This illustrates the issue with the shortnames.
